<style type="text/css">

.errors{
    display: none;
}

label.optional {
    margin-left: 1%;
}

#pro_tamanhos-element label {
        margin-left: 15px;
}

dd#pro_tamanhos-element {
    font-size: 13px;
    width: 636px;
    margin-left: 1%;
    margin-bottom: 2%;
    border-style: solid;
    border-color: #e6e7ed;
    border-width: 1px;
    display: inline-flex;
    height: 56px;
    margin-top: 5px;
    padding: 12px;
    border-left: 3px solid #4bae4f;
}

button#btn_enviar {
    margin-top: 30%;
}

</style>


<div class="row">
	<button type="button" class="btn bg-blue-grey" onClick="JavaScript: window.history.back();"><i class="fa fa-mail-reply"></i> Voltar</button>
		</br>
        </br>
        <?php

		  $mensages = $this->form->getMessages();
		  $this->validatorMensageProduct($mensages);
		
		?>
		<br/>
		<br/>
        <input  id ="categoria" type="hidden" name="categoria" value="<?php echo $this->categoria?>"/>
		<?php echo $this->form?>
<div id="#root-picker-outlet"></div>		
</div>