<!-- Statsbar -->
				<div class="statsBar">
					<div class="row">
						<div class="col-xs-12 col-md-4 i green">
							<a href="#" title="#" class="c">
								<h3 class="title">Total de vendas</h3>
								<div class="num">R$ 1.40.789</div>
							</a>
						</div>
							
						<div class="col-xs-12 col-md-4 i pink">
							<a href="#" title="#" class="c">
								<h3 class="title">Total a receber</h3>
								<div class="num">R$ 1.40.789</div>
							</a>
						</div>

						<div class="col-xs-12 col-md-4 i yellow">
							<a href="#" title="#" class="c">
								<h3 class="title">Meta</h3>
								<div class="num">140.000,00</div>
							</a>
						</div>
						
					</div>
				</div>