<div class="row">
	<button type="button" class="btn bg-blue-grey" onClick="JavaScript: window.history.back();"><i class="fa fa-mail-reply"></i> Voltar</button>
</br>
</br>
		<?php

		  //$mensages = $this->form->getMessages();
		  //var_dump($mensages);
		  //$this->validatorMensage($mensages);
		
		?>
		<br/>
		<br/>
		<h2 class="boxHeadline">Editar Categoria</h2>
		<h3 class="boxHeadlineSub">Edição de categoria CRM 700 Gauss</h3>

		<?php echo $this->form?>
<div id="#root-picker-outlet"></div>		
</div>