<?php
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $controller = $request->getControllerName();
?>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>
<button type="button" class="btn bg-blue-grey" onClick="JavaScript: window.history.back();"><i class="fa fa-mail-reply"></i> Voltar</button>
<a href="<?php echo $this->baseUrl()?>/usuarios/cadastrar">
<button type="button" class="btn bg-purple">+ Cadastrar Usuário</button>
</a>

<!-- Table Striped -->
<br/>
				<?php echo $this->paginator; ?>
				<div class="box rte box-without-bottom-padding">
					<h2 class="boxHeadline">Agregados do Revendedor: <span class="label label-info"><?php echo $this->nome?></span></h2>
					<h3 class="boxHeadlineSub">CRM 700 Gauss</h3>
					<div class="tableWrap table-responsive">
						<table class="table">
							<thead>
								 <tr>
						            <th>#Código</th>
						            <th>Nome</th>
						            <th>Telefone</th>
						            <th>Email</th>
						            <th>Permissão</th>
						            <th>Cadastrado</th>
						            <th>Ativo</th>
						            <th>Ação</th>
						        </tr>
							</thead>
							<tbody>
								<?php foreach ($this->lista as $key => $value):?>
								<tr>
									<th scope="row"><?php echo $value->usr_id ?></th>
						            <td><?php echo $value->usr_nome ?></td>
						            <td><?php echo $value->usr_celular ?></td>
						            <td><?php echo $value->usr_email ?></td>
						            <td><?php echo $value->usr_permissao ?></td>
						            <td><?php echo $this->dateTimeFormate($value->usr_data_cadastro) ?></td>
						            <td>
						            	<?php //echo $value->usr_ativo ?>
										<input type="checkbox" codigo-usuario="<?php echo $value->usr_id?>" class="ativo" name="ativo" <?php echo $check = ($value->usr_ativo!=0) ? 'checked' : ''; ?>>
						            </td>
						            <td>
						            	<?php if($value->usr_permissao=="vendedor"):?>
						            	<a href="#" title="Ver Carteira" class="text-light-gray"><i class="fa fa-suitcase"></i></a>
						            	<?php elseif($value->usr_permissao=="revendedor"):?>
						            	<a href="<?php echo $this->baseUrl()?>/usuarios/agregados/id/<?php echo $value->usr_id?>" title="Ver Agregados" class="text-light-gray"><i class="fa fa-users"></i></a>
						            	<?php endif;?>
						            	<a href="<?php echo $this->baseUrl()?>/usuarios/editar/id/<?php echo $value->usr_id?>" title="Editar usuário" class="text-light-gray"><i class="fa fa-pencil-square-o"></i></a>
						            	<a  href="javascript:void(0);" title="Excluir usuário" controller="<?php echo $controller?>" id="<?php echo $value->usr_id ?>" class="remove_item text-light-gray"><i class="fa fa-trash-o"></i></a>
						            </td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				<?php echo $this->paginator; ?>


   <!-- Search modal -->
   <div class="modal fade in" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="<?php echo $this->baseUrl()?>/usuarios/resultado" enctype="application/x-www-form-urlencoded" method="post">
                        <input type="text" id="nome_usuario" class="form-control" name="nome_usuario" placeholder="Digite o nome do Usuário...">
                        <button type="submit" class="btn">Procurar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>