<div class="row">
					<div class="col-xs-12 col-lg-3">
						<div class="box">
							<h2 class="boxHeadline">Eventos para Adicionar</h2>
							<h3 class="boxHeadlineSub">Arraste as atividades para o calendário</h3>

							<div id="external-events">
								<div class="fc-event external-event">Visitar Cliente Romero</div>
								<div class="fc-event external-event">Visitar Cliente Pedro</div>
								<div class="fc-event external-event">Pagar Fatura 700 Gauss</div>
								<p class="checkboxes">
									<label>
										<input type="checkbox" id="drop-remove">
										<span>remover depois de adicionar</span>
									</label>
								</p>
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-lg-9">
						<div class="box">
							<h2 class="boxHeadline">Agenda</h2>
							<h3 class="boxHeadlineSub">Utilize a agenda 700 Gauss para facilitar suas atividades diárias, faça dela sua rotina!</h3>
							
							<div id='calendar'></div>
						</div>
					</div>
				</div>