<!doctype html>
<html  lang="pt_br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Login | CRM 700 Gauss</title>
	<meta name="description" content="...">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- Icons -->
	<link rel="apple-touch-icon" href="<?php echo $this->baseUrl()?>/apple-touch-icon.png">
	
	<!-- CSS -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/jquery-ui.min.css">


    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/plugins/bootstrapvalidator/dist/css/bootstrapValidator.min.css"/>


	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/select2.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/font-awesome-4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/app.min.css">
	
	<!-- Modernizr -->
        <script src="<?php echo $this->baseUrl()?>/assets/js/modernizr-2.8.3.min.js"></script>

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
</head>
<body class="page-login">
	<!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="<?php echo $this->baseUrl()?>/http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	
	<div class="loginContentWrap">
		<div class="container">
		<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
		<?php foreach ($flashMessenger->getMessages() as $msg): ?>
		    <?php echo $msg ?>
		<?php endforeach; ?>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
					<div id="mensagem" style="display:none">
						<div class="alert alert-danger alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
						<strong>Erro</strong> - Usuário ou senhas inválidos
					</div>
					</div>
					<form role="form" id="login" >
						<div class="form-group">
							<input name="usuario" id="usuario" type="text" class="form-control simple-form-control" placeholder="Usuário" required >
							<i class="fa fa-user"></i>
						</div>
						<div class="form-group">
							<input name="senha" id="senha" type="password" class="form-control simple-form-control" placeholder="Password" required>
							<i class="fa fa-lock"></i>
						</div>
						
						<div class="form-group">
							<button type="submit" id="btn-login" class="btn btn-orange submit" >Login</button>
						</div>
					</form>
					<ul class="more">
						<li><a href="<?php echo $this->baseUrl()?>/login/solicitar-registro" title="#">Solicitar Registro</a></li>
						<li><a href="<?php echo $this->baseUrl()?>/login/recuperar-senha" title="#">Recuperar Senha</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<!-- JS -->
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-1.11.3.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-ui.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/select2.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/parsley.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/throttle-debounce.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery.shuffle.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/autosize.min.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl()?>/plugins/bootstrapvalidator/dist/js/bootstrapValidator.min.js"></script>
    <script type="text/javascript" src="<?=$this->baseUrl()?>/plugins/bootstrapvalidator/src/js/language/pt_BR.js"></script>

	<script src="<?php echo $this->baseUrl()?>/files_js/controllers/login/index.js"></script>

	<div class="visible-xs visible-sm extendedChecker"></div>
</body>
</html>