<!doctype html>
<html  lang="pt_br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Recuperar senha | CRM 700 Gauss</title>
	<meta name="description" content="...">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- Icons -->
	<link rel="apple-touch-icon" href="<?php echo $this->baseUrl()?>/apple-touch-icon.png">
	
	<!-- CSS -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/jquery-ui.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/select2.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/font-awesome-4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/app.min.css">
	
	<!-- Modernizr -->
	<script src="<?php echo $this->baseUrl()?>/assets/js/modernizr-2.8.3.min.js"></script>

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
</head>
<body class="page-login">
	<!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="<?php echo $this->baseUrl()?>/http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	
	<div class="loginContentWrap">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
					<div class="text-center">
						<h1 class="pageTitle">Recupere seu acesso</h1>
						<p>Digite seu email que enviaremos o método de recuperação</p>
					</div>
					<form data-parsley-validate>
						<div class="form-group">
							<input type="email" class="form-control simple-form-control" placeholder="Email" required data-parsley-error-message="Wrong e-mail format">
							<i class="fa fa-envelope"></i>
						</div>
						
						<div class="form-group">
							<button type="submit" class="btn btn-orange submit">Enviar recuperação</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<!-- JS -->
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-1.11.3.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-ui.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/select2.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/parsley.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/throttle-debounce.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/jquery.shuffle.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/autosize.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/raphael-min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/morris.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/Chart.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/chartist.min.js"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/js/app.min.js"></script>

	<div class="visible-xs visible-sm extendedChecker"></div>
</body>
</html>