<?php
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $controller = $request->getControllerName();
?>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>


<?php
	$authNamespace = new Zend_Session_Namespace('Carrinho');	
	$carrinho = $authNamespace->carrinho;

?>

<?php if(!empty($authNamespace->carrinho)):?>
	<?php $total = null;?>
	<?php $subtotal = null;?>

	<?php foreach ($carrinho as $key => $value):?>
		<?php foreach ($value["numeros"] as $indice => $valor):?>
			<?php $subtotal+= $valor * $value["valor"];
					$subtotal = $valor * $value["valor"];
					$total+= $subtotal;
			?>
	<?php endforeach;?>
	<?php endforeach;?>
<?php endif;?>




<style type="text/css">

	#alert_sucesso {
    color: #ffffff!important;
	}
	
	input.quantidade {
    max-width: 21px;
    background: transparent;
    border: none;
	}
</style>

<div class="boxHeader box">
		<h1 class="pageTitle">
			<a href="#" title="#">Onde você está!</a>
		</h1>
		<ol class="breadcrumb">
			<li><a href="#" style="color: #A29F9E;"><i class="zmdi zmdi-mouse zmdi-hc-fw"></i> Escolhendo produtos</a></li>
			<li><a href="#"><i class="zmdi zmdi-eye zmdi-hc-fw"></i> Verificando seu pedido</a></li>
			<li><a href="#" style="color: #A29F9E;"><i class="zmdi zmdi-card zmdi-hc-fw"></i> Efetuando pagamento</a></li>
		</ol>
</div>

<a href="<?php echo $this->baseUrl()?>/pedidos/grade">
<button type="button" class="btn bg-light-blue"><i class="fa fa-chevron-circle-left"></i>Continuar Comprando<i class="fa fa-cart-plus"></i></button>
</a>

<a href="<?php echo $this->baseUrl()?>/pedidos/carrinho/id/esvaziar">
<button type="button" class="btn btn-primary">Zerar Pedido<i class="fa fa-trash-o"></i></button>
</a>

<form  style="display: inline;" action="<?php echo $this->baseUrl()?>/pedidos/carrinho/" method="post">
<input type="hidden" name="atualizar" value="atualizar">
<?php if(!empty($total)):?>
	<input type="hidden" name="total" value="<?php echo $total?>">
<?php endif;?>	
<button type="submit" class="btn bg-light-green"><i class="zmdi zmdi-refresh-sync zmdi-hc-fw"></i> Atualizar Carrinho</button>
</form>

<?php if(!empty($authNamespace->carrinho)):?>
<a href="<?php echo $this->baseUrl()?>/pedidos/pagamento">
<button type="button"  id="botao_pagamento" class="btn bg-light-blue">Prosseguir para o pagamento<i class="fa fa-chevron-circle-right"></i></button>
</a>
				
<?php endif;?>

<!-- Table Striped -->
				<div class="box rte box-without-bottom-padding">
					<h2 class="boxHeadline">Conferência do(s) item(ns)</h2>
					<?php if(!empty($carrinho)):?>
						<div class="tableWrap table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>#Código</th>
										<th>Produto</th>
										<th>Numeração</th>
										<th>Quantidade</th>
										<th>Valor Unitário</th>
										<th>Subtotal</th>
										<th>Ação</th>
									</tr>
								</thead>
								<tbody>
									<?php $subtotal=null; ?>
									<?php $total=null; ?>
									<?php ksort($carrinho);?>
									<?php foreach ($carrinho as $key => $value):?>
										<?php ksort($value["numeros"]);?>
										<?php foreach ($value["numeros"] as $indice => $valor):?>
											<tr>
												<td><?php echo $key?></td>
												<th scope="row"><?php echo $value["nome"]?></th>
												<td><?php echo $indice?></td>
												<td>
													<a href="javascript:void(0)" class="subtrair_item" idprodutosub="<?php echo $key?>" numerosub="<?php echo $indice?>"> 
														<img src="<?php echo $this->baseUrl()?>/img/minus.png" style="max-width:15px" >
													</a>
													&nbsp;
													<span>
														<input class="quantidade" id="quantidade_<?php echo $key?>_<?php echo $indice?>" value="<?php echo $valor?>"/>
													</span>
													&nbsp;
													<a href="javascript:void(0)" class="somar_item" idprodutosoma="<?php echo $key?>" numerosoma="<?php echo $indice?>">
													<img src="<?php echo $this->baseUrl()?>/img/more.png" style="max-width:14px">
													</a>
												</td>
												<td>R$ <?php echo number_format( $value["valor"] , 2, ',', '.');?></td>
												<td>R$ <?php $subtotal+= $valor * $value["valor"];
														$subtotal = $valor * $value["valor"];
														echo number_format( $subtotal , 2, ',', '.');
														$total+= $subtotal;
												?></td>
												<td>
													<a  href="javascript:void(0);" numeracao="<?php echo $indice?>" idProdutoExcluir="<?php echo $key?>" title="Excluir item" controller="" id="" class="remover_item_do_carrinho text-light-gray"><i class="fa fa-trash-o"></i></a>
												</td>
											</tr>
										<?php endforeach;?>											
									<?php endforeach;?>		
									<tr>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td>Total</td>
												<td><span style="font-size: 16px;" class="label label-primary">R$<?php echo @number_format( $total , 2, ',', '.');?></span></td>
												<td></td>
											</tr>															
								</tbody>
							</table>
						</div>
					<?php else:?>	
					<div class="alert alert-warning alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
						<strong>Aviso</strong> - Seu carrinho de compras está vazio
					</div>
					<?php endif;?>

				</div>
				<br/>
				<!-- <button type="button" class="btn bg-light-blue total_item">TOTAL </button>				 -->