<style type="text/css">
	button.btn.bg-light-blue.total_item {
	    float: right;
	    margin-right: 30px;
	    margin-top: -17px;
	}
</style>


<a href="<?php echo $this->baseUrl()?>/pedidos/grade">
<button type="button" class="btn bg-purple">+ Faça pedido</button>
</a>

<!-- Table Striped -->
				<div class="box rte box-without-bottom-padding">
					<h2 class="boxHeadline">Pedido Número #4345</h2>
					<h3 class="boxHeadlineSub">detalhe do pedido</h3>
					
					<div class="tableWrap table-responsive">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>Produto</th>
									<th>Quantidade</th>
									<th>Valor Unitário</th>
									<th>Subtotal</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<th scope="row">Aconchego marrom cat. 10/11</th>
									<td>2</td>
									<td>R$100,00</td>
									<td>R$200,00</td>
								</tr>								

								<tr>
									<th scope="row">Aconchego preta</th>
									<td>1</td>
									<td>R$60,00</td>
									<td>R$60,00</td>
								</tr>								

								<tr>
									<th scope="row">Aconchego marrom cat. 10/11</th>
									<td>2</td>
									<td>R$100,00</td>
									<td>R$200,00</td>
								</tr>								
							</tbody>
						</table>
					</div>
				</div>

				<button type="button" class="btn bg-light-blue total_item">TOTAL R$460,00</button>