<?php
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $controller = $request->getControllerName();
?>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>


<?php include '../application/layouts/scripts/contadores.phtml' ?>


<a href="<?php echo $this->baseUrl()?>/pedidos/grade">
<button type="button" class="btn bg-purple">+ Faça pedido</button>
</a>

<!-- Table Striped -->
				<br/>
				<?php echo $this->paginator; ?>
				<div class="box rte box-without-bottom-padding">
					<h2 class="boxHeadline">Últimos Pedidos</h2>
					<h3 class="boxHeadlineSub">lista geral de pedidos</h3>
					
					<div class="tableWrap table-responsive">
						<table class="table table-striped">
							<thead>
								<tr>
									<th># Nº do Pedido</th>
									<th>Cliente</th>
									<th>Data</th>
									<th>Valor Total</th>
									<th>Status Fábrica</th>
									<th>Status Pagamento</th>
									<th>Ações</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($this->lista as $obj => $value):?>
								<tr>
									<th scope="row"><?php echo $value["ped_id"]?></th>
									<th scope="row"><?php echo $value["usr_nome"]?></th>
									<td><?php echo $this->dateTimeFormate($value["ped_data"])?></td>
									<td><?php echo $value["ped_valor"]?></td>
									<td><?php echo $value["ped_status"]?></td>
									<td><?php echo $value["ped_status_pagamento"]?></td>
									<td><span class="text-green"><strong><a href="<?php echo $this->baseUrl()?>/pedidos/detalhes">Detalhes</a></strong></span></td>
								</tr>	
								<?php endforeach;?>							
							</tbody>
						</table>
					</div>
				</div>
				<?php echo $this->paginator; ?>