<?php
	$auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
?>

<?php
	$authNamespace = new Zend_Session_Namespace('Carrinho');	
	$carrinho = $authNamespace->carrinho;
	$Credito = new Zend_Session_Namespace('Creditos');

?>

<?php $itens = null;?>
<?php $total = null;?>
<?php $subtotal = null;?>

<?php foreach ($carrinho as $key => $value):?>
	<?php foreach ($value["numeros"] as $indice => $valor):?>
		<?php $subtotal+= $valor * $value["valor"];
				$subtotal = $valor * $value["valor"];
				$total+= $subtotal;
		?>
<?php endforeach;?>
<?php endforeach;?>


<style type="text/css">
select#mes_aniversario {
    margin-top: 5px;
}

select#ano_aniversario {
    margin-top: 5px;
}

select#ano_validade {
    margin-top: 5px;
}

form#formCreditos {
    display: inline;
}

.col-xs-12.col-lg-8.show-grid {
    background-color: #f0f1f5!important;
}

</style>


<div class="boxHeader box">
					<h1 class="pageTitle">
						<a href="#" title="#">Onde você está!</a>
					</h1>
					<ol class="breadcrumb">
						<li><a href="#" style="color: #A29F9E;"><i class="zmdi zmdi-mouse zmdi-hc-fw"></i> Escolhendo produtos</a></li>
						<li><a href="#" style="color: #A29F9E;"><i class="zmdi zmdi-eye zmdi-hc-fw"></i> Verificando seu pedido</a></li>
						<li><a href="#"><i class="zmdi zmdi-card zmdi-hc-fw"></i> Efetuando pagamento</a></li>
					</ol>
</div>
<div id="botoes">
<button type="button" style="font-size: 12.5px;" id="creditos" class="btn bg-teal"><i class="fa fa-money"></i> Seus Créditos(<?php echo (!is_null($Credito->restante))? @number_format( $Credito->restante , 2, ',', '.') : number_format( $identity->usr_creditos , 2, ',', '.')  ?>)</button>
<br/>
<br/>

<a href='carrinho'>
	<button type='button' class='btn bg-light-blue'><i class="fa fa-chevron-circle-left"></i> Verificar Pedido<i class='zmdi zmdi-shopping-cart zmdi-hc-fw icon'></i></button>
</a>
<a href="<?php echo $this->baseUrl()?>/pedidos/grade">
<button type="button" class="btn bg-purple"><i class="fa fa-cart-plus"></i>Continuar Comprando</button>
</a>

<?php if(!$Credito->credito):?>
	<form action="<?php echo $this->baseUrl()?>/pedidos/pagamento" id="formCreditos" method="post">
		<input type="hidden" name="valorPedido" id="valorPedido" value="<?php echo $total ?>"/>	
		<input type="hidden" name="usarcreditos" id="usarcreditos" value="1"/>	
	<!-- Dinamica de crédito -->
	<button type="submit" class="btn bg-light-green"><i class="fa fa-money"></i> Usar Créditos </button>
	</form>
<?php endif; ?>


<?php if(!is_null($Credito->restante) && $total>$Credito->restante && $Credito->restante!=0):?>
	<form action="<?php echo $this->baseUrl()?>/pedidos/pagamento" id="formCreditos" method="post">
		<?php if($Credito->credito):?>
			<input type="hidden" name="valorPedido" id="valorPedido" value="<?php echo $total ?>"/>	
		<?php else:?>
			<input type="hidden" name="valorPedido" id="valorPedido" value="<?php echo $total ?>"/>	
		<?php endif;?>

	<input type="hidden" name="usarcreditos" id="usarcreditos" value="1"/>	
	<!-- Dinamica de crédito -->
	<button type="submit" class="btn bg-light-green"><i class="fa fa-money"></i> Usar Créditos </button>
	</form>
<?php endif; ?>

<!-- Verifica Novamente ao Atualizar o carrinho -->

<?php if(!empty($Credito->restante) && $Credito->restante > 0 && $Credito->total > 0):?>
	<form action="<?php echo $this->baseUrl()?>/pedidos/pagamento" id="formCreditos" method="post">	
		<button type="submit" class="btn bg-light-green"><i class="fa fa-money"></i> Usar Créditos (<?php echo @number_format( $Credito->restante , 2, ',', '.')?>)</button>
	</form>

	<button type="submit" class="btn btn-primary"><i class="fa fa-money"></i> Cancelar uso de Créditos</button>
<?php endif; ?>

<?php if(empty($Credito->restante)&& $Credito->credito):?>
	<form action="<?php echo $this->baseUrl()?>/pedidos/pagamento" id="formCreditos" method="post">
		<input type="hidden" name="cancelarcreditos" value="1"/>		
		<button type="submit" class="btn btn-primary"><i class="fa fa-money"></i> Cancelar uso de Créditos</button>
	</form>
<?php endif; ?>


<?php if($Credito->restante && $Credito->credito):?>
	<form action="<?php echo $this->baseUrl()?>/pedidos/pagamento" id="formCreditos" method="post">
		<input type="hidden" name="cancelarcreditos" value="1"/>		
		<button type="submit" class="btn btn-primary"><i class="fa fa-money"></i> Cancelar uso de Créditos</button>
	</form>
<?php endif; ?>
</div>	
</br>
</br>


	
	

<div class="row show-grid">
<?php if($Credito->credito):?>
	<div class="col-xs-12 col-md-8" style="width: 100%;">
		<h2 class="boxHeadline">Valor total da compra:</h2><span style="font-size: 16px;" class="label label-primary">R$<?php echo @number_format( $total , 2, ',', '.');?></span></br>
		<br/>
		<h2 class="boxHeadline">Créditos Usados:</h2><span style="font-size: 16px;" class="label label-primary">-R$<?php echo @number_format( $Credito->usado , 2, ',', '.');?></span></br>
		<br/>
		<h2 class="boxHeadline">Total a Pagar:</h2><span style="font-size: 16px;" class="label label-primary">R$<?php echo @number_format( $total - $Credito->usado, 2, ',', '.');?></span></br>
		<?php $valorFinal = number_format( $total - $Credito->usado, 2, '.', '.')?>
<?php else:?>
	<div class="col-xs-12 col-md-8" style="width: 100%;">
		<h2 class="boxHeadline">Valor total da compra:</h2><span style="font-size: 16px;" class="label label-primary">R$<?php echo @number_format( $total , 2, ',', '.');?></span></br>
		<?php $valorFinal = number_format( $total, 2, '.', '.') ?>
	</div>
<?php endif;?>
</br>
</div>



<?php if($valorFinal!='0.00'):?>

<h2 class="boxHeadline" id="titulo_forma_de_pagamento" style="margin-top: 4%!important">Formas de pagamento</h2>
<h3 class="boxHeadlineSub">Escolha como deseja pagar seu pedido</h3>
<div class="row">
						<div class="col-xs-12 col-lg-8 show-grid" style="margin-left: 17%">
							<ul class="nav nav-tabs" role="tablist">
								<li role="presentation" class="active"><a href="#tab-item-1" aria-controls="tab-item-1" role="tab" data-toggle="tab" aria-expanded="true"><i class="zmdi zmdi-card zmdi-hc-fw"></i> Cartão de crédito</a></li>
								<li role="presentation" class=""><a href="#tab-item-2" aria-controls="tab-item-2" role="tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-barcode"></i>&nbsp;&nbsp;Boleto</a></li>
								<li role="presentation" class=""><a href="#tab-item-3" aria-controls="tab-item-3" role="tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-user"></i>&nbsp;&nbsp;Negociar com o vendedor</a></li>																
							</ul>

							<div class="tab-content" id="topo_tab">
								<div role="tabpanel" class="tab-pane fade active in" id="tab-item-1">
									<form  id="form_cartao" role="form" enctype="application/x-www-form-urlencoded"  method="post">
										
										<input type="hidden" name="valorTotal" id="valorTotal" value="<?php echo $valorFinal ?>"/>	
										<input type="hidden" name="tokem" id="tokem" value="<?php echo $this->tokem ?>"/>
										
										<div class="form-group">
										
										<div id="info" class="alert alert-info alert-dismissible" role="alert">										
											<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
											<strong>Aviso</strong> - O pagamento poderá levar alguns minutos para ser processado
										</div>

										
										<div style="display:none" class="alert alert-danger alert-dismissible" role="alert" id="error_pag">
											<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
											<strong>Erro</strong> - <div id="msg_error"></div>
										</div>
										

										</div>	
										<div class="form-group">
											<label for="nome_cartao">Nome do dono do cartão</label>
											<input type="text" class="form-control" id="nome_cartao" name="nome_cartao" placeholder="Escreva como está no cartão">
										</div>
										
										<div class="row">
											<div class="col-xs-12 col-sm-4">
												<div class="form-group">
													<label for="dia_aniversario">Data de aniversário</label>
													<select class=" form-control js-select" id="dia_aniversario" name="dia_aniversario">
														<option disabled selected>- Dia -</option>
														<?php for ($i=1;$i<=31;$i++):?>
															<option value="<?php echo $i?>"><?php echo $i?></option>
														<?php endfor;?>
													</select>
												</div>
											</div>
											<div class="col-xs-12 col-sm-4">
												<div class="form-group">
													<label for="mes_aniversario"></label>
													<select class=" form-control js-select" id="mes_aniversario" name="mes_aniversario">
														<option disabled selected>- Mês -</option>
														<?php for ($i=1;$i<=12;$i++):?>
															<option value="<?php echo $i?>"><?php echo $i?></option>
														<?php endfor;?>
													</select>
												</div>
											</div>
											<div class="col-xs-12 col-sm-4">
												<div class="form-group">
													<label for="ano_aniversario"></label>
													<select class=" form-control js-select" id="ano_aniversario" name="ano_aniversario">
														<option disabled selected>- Ano -</option>
														<?php for ($i=1930;$i<=Date('Y')-18;$i++):?>
															<option value="<?php echo $i?>"><?php echo $i?></option>
														<?php endfor;?>
													</select>
												</div>
											</div>
										</div>

										<div class="form-group">
											<label for="cpf">CPF do dono do cartão</label>
											<input type="text" class="form-control" id="cpf" name="cpf" placeholder="ex: 064.782.785-48">
										</div>

										<div class="form-group">
											<img src="<?php echo $this->baseUrl()?>/img/cartoes.png">
										</div>	
										<div class="form-group">
											<label for="numero_cartao">Número do cartão de crédito</label>
											<input type="text" class="form-control" id="numero_cartao" name="numero_cartao" placeholder="">
											<input type="hidden" class="form-control" id="BrandCard" name="BrandCard" value="">
											<input type="hidden" class="form-control" id="TokemCard" name="TokemCard" value="">
										</div>

										<div class="row">
											<div class="col-xs-12 col-sm-4">
												<div class="form-group">
													<label for="mes_validade">Data de validade do cartão</label>
													<select class=" form-control js-select" id="mes_validade" name="mes_validade">
														<option disabled selected>- Mês -</option>
														<?php for ($i=1;$i<=12;$i++):?>
															<option value="<?php echo $i?>"><?php echo $i?></option>
														<?php endfor;?>
													</select>
												</div>
											</div>
											<div class="col-xs-12 col-sm-4">
												<div class="form-group">
													<label for="basicInputActive"></label>
													<select class=" form-control js-select" id="ano_validade" name="ano_validade">
														<option disabled selected>- Ano -</option>
														<?php for ($i=Date('Y');$i<=Date('Y')+15;$i++):?>
															<option value="<?php echo $i?>"><?php echo $i?></option>
														<?php endfor;?>
													</select>
												</div>
											</div>
										</div>

										<div class="form-group">
											<img src="<?php echo $this->baseUrl()?>/img/card_back.png" id="card_back" style="margin-bottom: 14px;">

											<label for="basicInput">Código de segurança do cartão (CCV)</label>
											<input type="text" maxlength="4" class="form-control" id="codigo_seguranca" name="codigo_seguranca" placeholder="Verifique na parte de trás do cartão">
										</div>


										<div class="form-group">
											<label for="basicInput">Parcelas</label>
											<select class=" form-control js-select" id="parcelas" name="parcelas">
														<option disabled selected>- Informe os dados do cartão para calcular -</option>
											</select>
										</div>
										<br/>
										<div class="form-group">
											<img src="<?php echo $this->baseUrl()?>/img/selo_pag.gif" id="selo_pag" style="margin-bottom: 14px;margin-top: -6px">
										</div>
										<button type="submit"  id="botao_pagamento" class="btn bg-purple total_item" style="float: right; margin-right: 0%;margin-bottom: 2%;">Efetuar Pagamento</button>

									</form>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="tab-item-2">
									
								</div>
								<div role="tabpanel" class="tab-pane fade" id="tab-item-3">
									
								</div>
							</div>
						</div>

						
					</div>
<?php else:?>					
	<button type="button" class="btn bg-purple btn-lg btn-block">Finalize seu Pedido</button>
	<!-- <button type="submit" class="btn bg-purple">Finalizar Pedido</button> -->
<?php endif;?>

<!-- <button type="button"  id="botao_pagamento" class="btn bg-light-blue total_item" style="margin-right: 0%">Efetuar Pagamento <i class="fa fa-chevron-circle-right"></i></button> -->
