<div class="row circleStats">
				
				<div class="col-md-2 col-sm-4 col-xs-6">
                	<div class="circleStatsItem red">
						<i class="fa  fa fa-thumbs-up"></i>
						<span class="plus">+</span>
						<span class="percent">%</span>
                    	<input type="text" value="50" class="orangeCircle" />
                	</div>
					<div class="box-small-title">Desempenho Geral</div>
				</div><!--/col-->
				
				<div class="col-md-2 col-sm-4 col-xs-6">
                	<div class="circleStatsItem blue">
                    	<i class="fa fa-thumbs-up"></i>
						<span class="plus">+</span>
						<span class="percent">%</span>
                    	<input type="text" value="8" class="blueCircle" />
                	</div>
					<div class="box-small-title">Revendedores Ativos</div>
				</div><!--/col-->
				
				<div class="col-md-2 col-sm-4 col-xs-6">
					<div class="circleStatsItem yellow">
                    	<i class="fa fa-thumbs-down"></i>
						<span class="plus">+</span>
						<span class="percent">%</span>
                    	<input type="text" value="12" class="yellowCircle" />
                	</div>
					<div class="box-small-title">Meta de Vendas</div>
				</div><!--/col-->
				
				<div class="col-md-2 col-sm-4 col-xs-6">
					<div class="circleStatsItem pink">
                    	<i class="fa fa-thumbs-up"></i>
						<span class="plus">+</span>
						<span class="percent">%</span>
                    	<input type="text" value="23" class="pinkCircle" />
                	</div>
					<div class="box-small-title">Inadimplência</div>
				</div><!--/col-->
				
				<div class="col-md-2 col-sm-4 col-xs-6">
                	<div class="circleStatsItem green">
                    	<i class="fa fa-thumbs-up"></i>
						<span class="plus">+</span>
						<span class="percent">%</span>
                    	<input type="text" value="34" class="greenCircle" />
                	</div>
					<div class="box-small-title">Devoluções</div>
				</div><!--/col-->

			</div><!--/row-->